# Site title
title = "Pamsagram's Travel, Food, and Adventures"
base_url = "https://andromeda-theme.netlify.app"
description = "Photography journal theme for Zola"
compile_sass = true

theme = "andromeda"

[extra]
header_links = [
    {name = "Zola", url = "https://www.getzola.org/"},
    {name = "Blog", url = "https://andromeda-theme.netlify.app"}
]
license = "CC BY-NC 2.0"
email = "pamsagramworld<at>gmail.com"
name = "Pamsagram"
# favicon = "/images/favicon.ico"
